jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      ...
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Packages & Libraries
        run: |
          uv pip install --all

      - name: Run isort (Import sorting)
        run: |
          uv run isort . --check --diff

      - name: Run black (Code formatting)
        run: |
          uv run black . --check

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U ${{ secrets.PG_USER }}; do
            sleep 1
          done

      - name: Run Django Migration
        run: |
          uv run python manage.py makemigrations
          uv run python manage.py migrate

      - name: Test python project
        run: |
          uv run python manage.py test
